
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int PROG = 2;
	public static final int CONST = 3;
	public static final int CLASS = 4;
	public static final int IF = 5;
	public static final int ELSE = 6;
	public static final int WHILE = 7;
	public static final int BREAK = 8;
	public static final int CONTINUE = 9;
	
	public static final int PRINT = 10;
	public static final int RETURN = 11;
	public static final int READ = 12;
	
	public static final int PLUS = 13;
	public static final int MINUS = 14;
	public static final int MULTIPLY = 15;
	public static final int DIVISION = 16;
	public static final int MOD = 17;
	
	public static final int EQUAL = 18;
	public static final int NOT_EQUAL = 19;
	public static final int GREATER = 20;
	public static final int GREATER_EQUAL = 21;
	public static final int LESS = 22;
	public static final int LESS_EQUAL = 23;
	
	public static final int AND = 24;
	public static final int OR = 25;
	
	public static final int ASSIGN = 26;
	public static final int INC = 27;
	public static final int DEC = 28;
	
	public static final int SEMI = 29;
	public static final int DOUBLE_DOT = 30;
	public static final int COMMA = 31;
	public static final int DOT = 32;
	
	public static final int LPAREN = 33;
	public static final int RPAREN = 34;
	public static final int LBRACKET = 35;
	public static final int RBRACKET = 36;
	public static final int LBRACE = 37;
	public static final int RBRACE = 38;
	
	public static final int POINTER_LIKE = 39;
	
	public static final int VOID = 40;
	public static final int NUMBER = 41;
	public static final int IDENT = 42;
	
	public static final int APOS = 43;
	
	public static final int TRUE = 44;
	public static final int FALSE = 45;
	
	public static final int EXTENDS = 46;
	public static final int FOREACH = 47;
	
}

